### ISSUE TITLE
Potential bias in ASCII Selection

### ISSUE THREAD

**Issue by HLSiira** [Collinz4/sslg5#1]
I only halfway follow some of this, the rest may as well be Spanish, and I'm not entirely sure my math is correct, or if it even matters in regards to the overall cipher, however I think you've biased your random generator towards characters 33 - 65 in lines 24 to 32 in KeyManager.java

Characters 66 to 127 have a 1 in 127 chance of being selected, while characters 33 to 65 have a 2 in 127 chance; examples:
Char 33 is both 33/127 and 00/127
Char 65 is both 65/127 and 32/127
Char 66 is only 66/127
Char 78 is only 78/127

In order to limit this bias, you might want to consider changing the line to something like:
int temp = ( r.nextInt(94) + 33 ) ;

**Comment by HLSiira** [comment]
Plus doing so could also lead the code to go from:  
`
for(int i = 0; i < 25; i++) {
            int temp = r.nextInt(127);
            
            if(temp < 33) {
                temp += 33;
            }
            
            key += Character.toString((char) temp);
}
`
To: 
`        for(int i = 0; i < 25; i++) {
            key += Character.toString((char) (r.nextInt(94) + 33));
}`

**Comment by Collinz4** [comment]
Thank you for catching this issue, I do agree that the key generator's output isn't uniformly distributed because of my logic. Although I do not see it posing an issue to the rest of the cipher I will change it as the method nextInt() does have a uniformly distributed output. I should commit the changes to Github in a day or two.
